OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4o-mini"

SPOTIFY_CLIENT_ID = "77a1ee1387914f8aa2d6708d4cb50c03"
SPOTIFY_CLIENT_SECRET = "4c187e5e2c5e4ddb9cca6f02af2cf2ca"
GENIUS_TOKEN = "1yM4HJtkhOJXoqAqyeoh0qK_EpT2PXq1pHMf0qzuA3KnNjPIAgoFLctlkm9CPerJ"
